CREATE TABLE order
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_pair VARCHAR(50)      NOT NULL,
    order_type VARCHAR(50)      NOT NULL,
    status     VARCHAR(50)      NOT NULL DEFAULT 'NEW',
    quantity   DOUBLE PRECISION NOT NULL,
    price      DOUBLE PRECISION NOT NULL,
    match_engine_status VARCHAR(50) DEFAULT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
