CREATE TABLE orders
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT           NOT NULL,
    order_type          VARCHAR(50)      NOT NULL,
    trade_pair          VARCHAR(50)      NOT NULL,
    status              VARCHAR(50)      NOT NULL DEFAULT 'NEW',
    quantity            DOUBLE PRECISION NOT NULL,
    price               DOUBLE PRECISION NOT NULL,
    match_engine_status VARCHAR(50),
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    PRIMARY KEY (id)
);
