CREATE TABLE orders
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    order_type          VARCHAR(50) NOT NULL,
    trade_pair          VARCHAR(50) NOT NULL,
    trade_side          VARCHAR(50) NOT NULL,
    status              VARCHAR(50) NOT NULL DEFAULT 'NEW',
    market_type         VARCHAR(50),
    quantity            NUMERIC(36,18) NOT NULL,
    price               NUMERIC(36,18) NOT NULL,
    match_engine_status VARCHAR(50),
    expire_days         BIGINT,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP
);