###User Signin
POST http://{{host}}/profile/open/v1/user/signin
Request-Id: 1234
Content-Type: application/json

{
  "userName": "matin111@gmail.com",
  "password": "matin111"
}
> {%
client.test("Status code is 200", function () {
    client.assert(response.status === 200, "Expected status 200");
});

client.test("Access token exists", function () {
    client.assert(response.body.accessToken !== undefined, "Missing accessToken object");
    client.assert(response.body.accessToken.accessToken !== "", "accessToken is empty");
});

client.test("Access token expiration exists", function () {
    client.assert(response.body.accessToken.expirationDate !== "", "accessToken expiration missing");
});

client.test("Refresh token exists", function () {
    client.assert(response.body.refreshToken !== undefined, "Missing refreshToken object");
    client.assert(response.body.refreshToken.refreshToken !== "", "refreshToken is empty");
});
a
client.test("Refresh token expiration exists", function () {
    client.assert(response.body.refreshToken.expirationDate !== "", "refreshToken expiration missing");
});

client.test("User type is returned", function () {
    client.assert(response.body.userType !== undefined, "userType missing");
});

client.global.set("loginToken", response.body.accessToken.accessToken);

%}



###create Wallet
POST http://{{host}}/wallet/api/v1/user/create-wallet
Authorization: Bearer {{loginToken}}
Request-Id: 333
Content-Type: application/json

{
  "assets": [
    {
      "balance": 0,
      "blockedBalance": 0,
      "assetType": "BTC"
    },
    {
      "balance": 0,
      "blockedBalance": 0,
      "assetType": "ETH"
    },
    {
      "balance": 1000,
      "blockedBalance": 100,
      "assetType": "USDT"
    },
    {
      "balance": 500,
      "blockedBalance": 0,
      "assetType": "EUR"
    },
    {
      "balance": 250,
      "blockedBalance": 50,
      "assetType": "USD"
    }
  ]
}

> {%
client.test("Status code is 200", function () {
    client.assert(response.status === 200, "Expected status 200");
});

client.test("Wallet contains assets", function () {
    client.assert(response.body.assets !== undefined, "assets missing");
    client.assert(response.body.assets.length > 0, "assets list is empty");
});

client.test("Check BTC exists", function () {
    const btc = response.body.assets.find(a => a.assetType === "BTC");
    client.assert(btc !== undefined, "BTC asset missing");
});

client.test("Check ETH exists", function () {
    const eth = response.body.assets.find(a => a.assetType === "ETH");
    client.assert(eth !== undefined, "ETH asset missing");
});

client.test("Check USDT exists", function () {
    const usdt = response.body.assets.find(a => a.assetType === "USDT");
    client.assert(usdt !== undefined, "USDT asset missing");
});

client.test("Check EUR exists", function () {
    const eur = response.body.assets.find(a => a.assetType === "EUR");
    client.assert(eur !== undefined, "EUR asset missing");
});

client.test("Check USD exists", function () {
    const usd = response.body.assets.find(a => a.assetType === "USD");
    client.assert(usd !== undefined, "USD asset missing");
});
%}
