spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hiebernate:
      ddl-auto: none

  flyway:
    enabled: false

