plugins {
    id 'application'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'org.flywaydb.flyway' version '10.20.0'
}


application {
    mainClass = 'com.exchange.profile.ProfileApp'
}

repositories {
    mavenCentral()
    maven {
        url "https://maven.keycloak.org"
    }
}

ext {
    springCloudVersion = "2023.0.3"   // Latest compatible with Spring Boot 3.5.x
    resilience4jVersion = "2.2.0"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations.all {
    exclude group: 'commons-logging', module: 'commons-logging'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Micrometer
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // Database
    implementation 'org.postgresql:postgresql:42.7.3'

    // Flyway
    implementation "org.flywaydb:flyway-core:10.20.0"
    implementation "org.flywaydb:flyway-database-postgresql:10.20.0"

    // Spring Cloud
   // implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'org.springframework.cloud:spring-cloud-config-client'

    // Resilience4j
    implementation "io.github.resilience4j:resilience4j-spring-boot3:${resilience4jVersion}"

    // logs
    implementation 'de.siegmar:logback-gelf:4.0.0'
    implementation("org.zalando:logbook-spring-boot-starter:3.12.0")
    implementation("org.zalando:logbook-json:3.12.0")
    implementation("org.zalando:logbook-core:3.12.0")

    // Jackson
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // OAuth2
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

    // Keycloak
    implementation 'org.keycloak:keycloak-spring-boot-starter:21.1.1'
    implementation 'org.keycloak:keycloak-admin-client:26.0.6'

    implementation 'com.opencsv:opencsv:5.9'
    implementation libs.guava

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Tests
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
