Spring:
  kafka:
    bootstrap-servers: localhost:9092

  data:
    mongodb:
      uri: mongodb://me_user:me@localhost:27017/me?authSource=me





custom-config:
  kafka:
    sendmessage-output-message:
      topic: send-message
    event-output-message:
      topic: event-topic
    me-create-update-output-message:
      topic: me-create-update-topic


