Spring:
  kafka:
    bootstrap-servers: localhost:9092


custom-config:
  kafka:
    savematchingEngine-output-message:
      topic: save-matching-engine


 #   updatematchingEngine-output-message:
#      topic: updatematchingEngine-message