spring:
  data:
    mongodb:
      uri: mongodb://eventmanager_user:eventmanager@localhost:27017/eventmanager?authSource=eventmanager
  kafka:
    bootstrap-servers: localhost:9092


  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.150
    metadata-map:
      versions: ${version}
      metrics.path: /eventmanager/actuator/prometheus
      health.path: /eventmanager/actuator/health
      context-path: /eventmanager
      management.context-path: /eventmanager