server:
  port: 8085
  servlet:
    context-path: /event
  shutdown: graceful


spring:
  flyway:
    enabled: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

camel:
  springboot:
    jmx-enabled: true



eureka:
  instance:
    metadata-map:
      prometheus.path: /event/actuator/prometheus
      context.path: /event
api:
  version: v1
  prefix:
    secure: /api/${api.version}
    open: /open/${api.version}
    internal: /_api/${api.version}


