stages:
 - build
 - deploy
build-dev:
 before_script:
  - 'chmod +x gradlew'
 script:
  - ./gradlew clean
  - ./gradlew build -x test
  - docker build --build-arg JAR_FILE=build/libs/*.jar -t oms:latest .
  - docker push registry.gitlab.com/group-exchange/oms:dev-1.0.0
 only:
  - develop
 stage: build
 tags:
  - dev
deploy-dev:
 script:
  - docker stop authentication || echo "Container already stopped"
  - docker rm authentication || echo "Container already removed"
  - docker run -d --net exchange-network -p 8084:8084 --name oms -v /logs:/logs -m 310m -e "SPRING_PROFILES_ACTIVE=development"  --link discovery:discovery registry.gitlab.com/group-exchange/oms:dev-1.0.0
 only:
  - develop
 stage: deploy
 tags:
  - dev
