###User Signin
POST http://{{host}}/profile/open/v1/user/signin
Request-Id: 123
Content-Type: application/json

{
  "userName": "matin111@gmail.com",
  "password": "matin111"
}
> {%
client.test("Status code is 200", function () {
    client.assert(response.status === 200, "Expected status 200");
});

client.test("Access token exists", function () {
    client.assert(response.body.accessToken !== undefined, "Missing accessToken object");
    client.assert(response.body.accessToken.accessToken !== "", "accessToken is empty");
});

client.test("Access token expiration exists", function () {
    client.assert(response.body.accessToken.expirationDate !== "", "accessToken expiration missing");
});

client.test("Refresh token exists", function () {
    client.assert(response.body.refreshToken !== undefined, "Missing refreshToken object");
    client.assert(response.body.refreshToken.refreshToken !== "", "refreshToken is empty");
});

client.test("Refresh token expiration exists", function () {
    client.assert(response.body.refreshToken.expirationDate !== "", "refreshToken expiration missing");
});

client.test("User type is returned", function () {
    client.assert(response.body.userType !== undefined, "userType missing");
});

client.global.set("loginToken", response.body.accessToken.accessToken);

%}


###Set user Profile
POST http://{{host}}/profile/api/v1/set-profile
Authorization: Bearer {{loginToken}}
Request-Id: 128
Content-Type: application/json

{
   "firstName": "Martin1111",
   "lastName": "Musterman",
   "phoneNumber": "06995858545",
   "genderType":"MALE",
   "birthday": "1990-11-01",
   "address": "Wien 1110"
}

> {%
client.test("Status code is 200", function () {
    client.assert(response.status === 200, "Expected status 200");
});

client.test("First name matches", function () {
    client.assert(response.body.firstName === "Martin", "firstName mismatch");
});

client.test("Last name matches", function () {
    client.assert(response.body.lastName === "Musterman", "lastName mismatch");
});

client.test("Phone number matches", function () {
    client.assert(response.body.phoneNumber === "06995858545", "phoneNumber mismatch");
});

client.test("Gender type matches", function () {
    client.assert(response.body.genderType === "MALE", "genderType mismatch");
});

client.test("Birthday matches", function () {
    client.assert(response.body.birthday === "1990-11-01", "birthday mismatch");
});

client.test("Address matches", function () {
    client.assert(response.body.address === "Wien 1110", "address mismatch");
});

client.test("Email exists", function () {
    client.assert(response.body.email !== undefined, "email missing");
    client.assert(response.body.email !== "", "email empty");
});

client.test("User status exists", function () {
    client.assert(response.body.status !== undefined, "status missing");
});
 %}