spring:
  kafka:
    bootstrap-servers: localhost:9096
    consumer:
      group-id: wallet
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer







#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    enabled: false
#  instance:
#    hostname: profile
#    appname: profile