plugins {
    id 'application'
    id 'me.champeau.jmh' version '0.7.2'
}

repositories {
    mavenCentral()
    gradlePluginPortal() // Add this line to include the Gradle Plugin Portal
}

dependencies {

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.4'


    // Use JUnit Jupiter for testing.
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Benchmark Testing
    implementation 'org.openjdk.jmh:jmh-core:1.37'
    annotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
    // Guava
    implementation libs.guava
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
