plugins {
    id 'application'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'me.champeau.jmh' version '0.7.2'
}

repositories {
    mavenCentral()
    gradlePluginPortal() // Add this line to include the Gradle Plugin Portal
}

dependencies {

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.5'

    // ---- SBE generated codecs (shared with core) ----
    implementation 'org.agrona:agrona:2.1.0'

    // Use JUnit Jupiter for testing.
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Benchmark Testing
    implementation 'org.openjdk.jmh:jmh-core:1.37'
    annotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
    // Guava
    implementation libs.guava
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        java {
            srcDir "$rootDir/core/build/generated-src/sbe"
        }
    }
}

compileJava.dependsOn ':core:generateSbe'

tasks.named('test') {
    useJUnitPlatform()
}
