server:
  port: 8089
  shutdown: graceful
  servlet:
    context-path: /

api:
  version: v1
  prefix:
    secure: /api/${api.version}
    open: /open/${api.version}
    internal: /_api/${api.version}

spring:
  application:
    name: core-gateway

  cloud:
    config:
      enabled: false


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true