server:
  port: 8090
  shutdown: graceful
  servlet:
    context-path: /oms

spring:
  application:
    name: oms
  cloud:
    config:
      enabled: false



springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html



api:
  version: v1
  prefix:
    secure: /api/${api.version}
    open: /open/${api.version}
    internal: /_api/${api.version}

custom-config:
  kafka:
    event-output-message:
      topic: event-topic

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true


resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s


    instances:
      me-instance:
        base-config: default
      wallet-instance:
        base-config: default

  retry:
    configs:
      default:
        max-attempts: 2
        wait-duration: 500ms
        exponential-backoff-multiplier: 2


    instances:
      me-instance:
        base-config: default
      wallet-instance:
        base-config: default